//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Boolean @__actions_default_in_Grab;
        
        public static SteamVR_Action_Pose @__actions_default_in_Pose;
        
        public static SteamVR_Action_Skeleton @__actions_default_in_SkeletonLeftHand;
        
        public static SteamVR_Action_Skeleton @__actions_default_in_SkeletonRightHand;
        
        public static SteamVR_Action_Boolean @__actions_default_in_HeadsetOnHead;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TriggerClick;
        
        public static SteamVR_Action_Boolean @__actions_default_in_MenuHider;
        
        public static SteamVR_Action_Boolean @__actions_default_in_VolumeDecreaseClick;
        
        public static SteamVR_Action_Boolean @__actions_default_in_VolumeIncreaseClick;
        
        public static SteamVR_Action_Vibration @__actions_default_out_Haptic;
        
        public static SteamVR_Action_Pose @__actions_mixedreality_in_ExternalCamera;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.@__actions_default_in_Grab.Initialize();
            SteamVR_Input.@__actions_default_in_Pose.Initialize();
            SteamVR_Input.@__actions_default_in_SkeletonLeftHand.Initialize();
            SteamVR_Input.@__actions_default_in_SkeletonRightHand.Initialize();
            SteamVR_Input.@__actions_default_in_HeadsetOnHead.Initialize();
            SteamVR_Input.@__actions_default_in_TriggerClick.Initialize();
            SteamVR_Input.@__actions_default_in_MenuHider.Initialize();
            SteamVR_Input.@__actions_default_in_VolumeDecreaseClick.Initialize();
            SteamVR_Input.@__actions_default_in_VolumeIncreaseClick.Initialize();
            SteamVR_Input.@__actions_default_out_Haptic.Initialize();
            SteamVR_Input.@__actions_mixedreality_in_ExternalCamera.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.@__actions_default_in_Grab = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_Grab")));
            Valve.VR.SteamVR_Input.@__actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonLeftHand")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonRightHand")));
            Valve.VR.SteamVR_Input.@__actions_default_in_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_HeadsetOnHead")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TriggerClick = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TriggerClick")));
            Valve.VR.SteamVR_Input.@__actions_default_in_MenuHider = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_MenuHider")));
            Valve.VR.SteamVR_Input.@__actions_default_in_VolumeDecreaseClick = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_VolumeDecreaseClick")));
            Valve.VR.SteamVR_Input.@__actions_default_in_VolumeIncreaseClick = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_VolumeIncreaseClick")));
            Valve.VR.SteamVR_Input.@__actions_default_out_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_Haptic")));
            Valve.VR.SteamVR_Input.@__actions_mixedreality_in_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_mixedreality_in_ExternalCamera")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Grab,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_HeadsetOnHead,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuHider,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeDecreaseClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeIncreaseClick,
                    Valve.VR.SteamVR_Input.@__actions_default_out_Haptic,
                    Valve.VR.SteamVR_Input.@__actions_mixedreality_in_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Grab,
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_HeadsetOnHead,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuHider,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeDecreaseClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeIncreaseClick,
                    Valve.VR.SteamVR_Input.@__actions_mixedreality_in_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[] {
                    Valve.VR.SteamVR_Input.@__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    Valve.VR.SteamVR_Input.@__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_mixedreality_in_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Grab,
                    Valve.VR.SteamVR_Input.@__actions_default_in_HeadsetOnHead,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuHider,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeDecreaseClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeIncreaseClick};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Grab,
                    Valve.VR.SteamVR_Input.@__actions_default_in_HeadsetOnHead,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuHider,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeDecreaseClick,
                    Valve.VR.SteamVR_Input.@__actions_default_in_VolumeIncreaseClick};
        }
    }
}
